<?php



return [
    'allowed_isps' => [
       'AT&T',
        'Verizon FiOS',
        'SpaceX Starlink',
		'Charter Communications Inc',
		'MTN NIGERIA Communication limited',
		'AT&T Services, Inc.',
		'Nubes, LLC',
		'Verizon Communications',
		'CenturyLink Communications, LLC',
		'Cogent Communications',
		'Comcast Cable Communications',
		'T-Mobile USA, Inc.',
		'Verizon Business',
		'Spectrum',
		'Cablevision Systems Corp.',
		'Static IP Services',
		'Xchange Telecom Corp.',
		'Charter Communications',
		'Cox Communications Inc.',
		'Frontier Communications Solutions',
		'Southern New England Telephone Company and SNET America',
		'Crown Castle Fiber LLC',
		'Frontier Communications of America, Inc.',
		'Consolidated Communications, Inc.',
		'Multacom Corporation',
		'Frontier Communications Corporation',
		'One Internet America, LLC',
		'Honest Networks, LLC',
		'CenturyLink Communications',
		'Peoples Communications Inc',
		'CABLE ONE, INC.',
		'TDS TELECOM',
		'Tombigbee Communications, LLC',
		'Phenix Cable',
		'Pavlov Media Inc',
		'MTN NIGERIA',
		'Globacom Limited',
		'Cable ONE',
		'CenturyLink',
		'Grafton Technologies, Inc.',
		'SkyRider Communications, Inc.',
    ],

    'allowed_countries' => [
'United States',
'Nigeria',
],
];

